apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-net
spec:
  config: |- 
    {
      "cniVersion": "0.3.1",
      "name": "ipvlan-net",
      "type": "ipvlan",
      "mode": "l2",
      "master": "ens10",
      "ipam": {
        "type": "static",
        "addresses": [
           {
             "address": "192.168.100.101/24"
           },
           {
             "address": "192.168.100.102/24"
           }
        ]
      }
    }
